// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/0xsj/hexagonal-go/internal/identity/application/command"
	"github.com/0xsj/hexagonal-go/internal/identity/application/query"
	"github.com/0xsj/hexagonal-go/internal/identity/infrastructure/repository"
	v1 "github.com/0xsj/hexagonal-go/internal/identity/interface/http/v1"
	"github.com/0xsj/hexagonal-go/pkg/provider"
)

// Injectors from wire.go:

// InitializeApp wires up the entire application.
func InitializeApp() (*App, func(), error) {
	logger := provider.ProvideLogger()
	db, cleanup, err := provider.ProvideDatabase(logger)
	if err != nil {
		return nil, nil, err
	}
	publisher := provider.ProvideEventBus(logger)
	postgresUserRepository := repository.NewPostgresUserRepository(db)
	registerUserCommand := command.NewRegisterUserCommand(postgresUserRepository, publisher, logger)
	loginCommand := command.NewLoginCommand(postgresUserRepository, publisher, logger)
	verifyEmailCommand := command.NewVerifyEmailCommand(postgresUserRepository, publisher, logger)
	getUserQuery := query.NewGetUserQuery(postgresUserRepository)
	listUsersQuery := query.NewListUsersQuery(postgresUserRepository)
	handler := v1.NewHandler(registerUserCommand, loginCommand, verifyEmailCommand, getUserQuery, listUsersQuery, logger)
	app := &App{
		Logger:          logger,
		DB:              db,
		EventBus:        publisher,
		IdentityHandler: handler,
	}
	return app, func() {
		cleanup()
	}, nil
}
