// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/0xsj/hexagonal-go/cmd/api/config"
	"github.com/0xsj/hexagonal-go/internal/audit/application/subscriber"
	repository2 "github.com/0xsj/hexagonal-go/internal/audit/infrastructure/repository"
	"github.com/0xsj/hexagonal-go/internal/identity/application/command"
	"github.com/0xsj/hexagonal-go/internal/identity/application/query"
	"github.com/0xsj/hexagonal-go/internal/identity/infrastructure/repository"
	v1 "github.com/0xsj/hexagonal-go/internal/identity/interface/http/v1"
	command2 "github.com/0xsj/hexagonal-go/internal/notifications/application/command"
	subscriber2 "github.com/0xsj/hexagonal-go/internal/notifications/application/subscriber"
	repository3 "github.com/0xsj/hexagonal-go/internal/notifications/infrastructure/repository"
	"github.com/0xsj/hexagonal-go/pkg/database/postgres"
	"github.com/0xsj/hexagonal-go/pkg/email"
	"github.com/0xsj/hexagonal-go/pkg/observability/logger/console"
	"github.com/0xsj/hexagonal-go/pkg/provider"
)

// Injectors from wire.go:

// InitializeApp wires up the entire application.
func InitializeApp(cfg *config.AppConfig) (*App, func(), error) {
	options := ProvideLoggerOptions(cfg)
	logger := provider.ProvideLogger(options)
	postgresConfig := ProvidePostgresConfig(cfg)
	db, cleanup, err := provider.ProvideDatabase(postgresConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	publisher := provider.ProvideEventBus(logger)
	postgresUserRepository := repository.NewPostgresUserRepository(db)
	registerUserCommand := command.NewRegisterUserCommand(postgresUserRepository, publisher, logger)
	loginCommand := command.NewLoginCommand(postgresUserRepository, publisher, logger)
	verifyEmailCommand := command.NewVerifyEmailCommand(postgresUserRepository, publisher, logger)
	getUserQuery := query.NewGetUserQuery(postgresUserRepository)
	listUsersQuery := query.NewListUsersQuery(postgresUserRepository)
	handler := v1.NewHandler(registerUserCommand, loginCommand, verifyEmailCommand, getUserQuery, listUsersQuery, logger)
	postgresRepository := repository2.NewPostgresRepository(db)
	eventSubscriber := subscriber.NewEventSubscriber(postgresRepository, logger)
	repositoryPostgresRepository := repository3.NewPostgresRepository(db)
	emailConfig := ProvideEmailConfig(cfg)
	sender := provider.ProvideEmailSender(emailConfig)
	sendNotificationCommand := command2.NewSendNotificationCommand(repositoryPostgresRepository, sender, logger)
	userEventSubscriber := subscriber2.NewUserEventSubscriber(sendNotificationCommand, logger)
	app := &App{
		Logger:                 logger,
		DB:                     db,
		EventBus:               publisher,
		IdentityHandler:        handler,
		AuditSubscriber:        eventSubscriber,
		NotificationSubscriber: userEventSubscriber,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// ProvidePostgresConfig extracts database config from AppConfig.
func ProvidePostgresConfig(cfg *config.AppConfig) postgres.Config {
	return cfg.Database
}

// ProvideLoggerOptions extracts logger options from AppConfig.
func ProvideLoggerOptions(cfg *config.AppConfig) console.Options {
	return cfg.Logger
}

// ProvideEmailConfig extracts email config from AppConfig.
func ProvideEmailConfig(cfg *config.AppConfig) email.Config {
	return cfg.Email
}
