// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/0xsj/hexagonal-go/internal/identity/application/command"
	"github.com/0xsj/hexagonal-go/internal/identity/application/query"
	"github.com/0xsj/hexagonal-go/internal/identity/infrastructure/repository"
	"github.com/0xsj/hexagonal-go/internal/identity/interface/http/v1"
	"github.com/0xsj/hexagonal-go/pkg/provider"
)

// Injectors from wire.go:

// InitializeApp wires up the entire application.
func InitializeApp() (*App, func(), error) {
	logger := provider.ProvideLogger()
	db, cleanup, err := provider.ProvideDatabase(logger)
	if err != nil {
		return nil, nil, err
	}
	mockUserRepository := repository.NewMockUserRepository()
	registerUserCommand := command.NewRegisterUserCommand(mockUserRepository)
	loginCommand := command.NewLoginCommand(mockUserRepository)
	verifyEmailCommand := command.NewVerifyEmailCommand(mockUserRepository)
	getUserQuery := query.NewGetUserQuery(mockUserRepository)
	listUsersQuery := query.NewListUsersQuery(mockUserRepository)
	handler := v1.NewHandler(registerUserCommand, loginCommand, verifyEmailCommand, getUserQuery, listUsersQuery, logger)
	app := &App{
		Logger:          logger,
		DB:              db,
		IdentityHandler: handler,
	}
	return app, func() {
		cleanup()
	}, nil
}
