// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package identity

import (
	"github.com/0xsj/hexagonal-go/internal/identity/application/command"
	"github.com/0xsj/hexagonal-go/internal/identity/application/query"
	"github.com/0xsj/hexagonal-go/internal/identity/domain/user"
	"github.com/0xsj/hexagonal-go/internal/identity/infrastructure/repository"
	"github.com/0xsj/hexagonal-go/internal/identity/interface/http/v1"
	"github.com/0xsj/hexagonal-go/pkg/database"
	"github.com/0xsj/hexagonal-go/pkg/observability/logger"
	"github.com/google/wire"
)

// Injectors from provider.go:

func ProvideModule(db database.DB, log logger.Logger) (*v1.Handler, error) {
	mockUserRepository := repository.NewMockUserRepository()
	registerUserCommand := command.NewRegisterUserCommand(mockUserRepository)
	loginCommand := command.NewLoginCommand(mockUserRepository)
	verifyEmailCommand := command.NewVerifyEmailCommand(mockUserRepository)
	getUserQuery := query.NewGetUserQuery(mockUserRepository)
	listUsersQuery := query.NewListUsersQuery(mockUserRepository)
	handler := v1.NewHandler(registerUserCommand, loginCommand, verifyEmailCommand, getUserQuery, listUsersQuery, log)
	return handler, nil
}

// provider.go:

var IdentitySet = wire.NewSet(repository.NewMockUserRepository, wire.Bind(new(user.Repository), new(*repository.MockUserRepository)), command.NewRegisterUserCommand, command.NewLoginCommand, command.NewVerifyEmailCommand, query.NewGetUserQuery, query.NewListUsersQuery, v1.NewHandler)
